#!/usr/bin/env bash
#
# scripts/umbra-verify.sh
#
# UMBRA-INFRA-001 — deterministic local verification pipeline.
#
# Runs the standard Umbra pre-iteration validation commands, captures their
# stdout + stderr, and writes a Markdown report under
# docs/engineering/agents/reports/hooks/. Records every command regardless of
# individual failure and exits 0 only if every required command passed.
#
# Usage:
#   bash scripts/umbra-verify.sh
#   bash scripts/umbra-verify.sh --with-dev-smoke
#   bash scripts/umbra-verify.sh --help
#
# Exit codes:
#   0   all required commands passed (final status PASS)
#   1   one or more required commands failed (final status FAIL)
#   2   invocation error (unknown argument, failed to chdir / mkdir report dir)
#

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT" || {
  echo "umbra-verify: failed to cd to $REPO_ROOT" >&2
  exit 2
}

REPORT_DIR="$REPO_ROOT/docs/engineering/agents/reports/hooks"
if ! mkdir -p "$REPORT_DIR"; then
  echo "umbra-verify: failed to create $REPORT_DIR" >&2
  exit 2
fi

TIMESTAMP_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
TIMESTAMP_FILE="$(date -u +%Y%m%dT%H%M%SZ)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")"
COMMIT="$(git rev-parse HEAD 2>/dev/null || echo "unknown")"
GIT_STATUS="$(git status --short --branch 2>/dev/null || echo "(unavailable)")"

RUN_DEV_SMOKE=0
for arg in "$@"; do
  case "$arg" in
    --with-dev-smoke) RUN_DEV_SMOKE=1 ;;
    -h|--help)
      sed -n '2,20p' "$0"
      exit 0
      ;;
    *)
      echo "umbra-verify: unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

NAMES=()
DESCS=()
EXITS=()
OUTPUT_FILES=()

run_cmd() {
  local name="$1"
  local desc="$2"
  shift 2
  local out
  out="$(mktemp -t umbra-verify.XXXXXX)"
  if "$@" >"$out" 2>&1; then
    EXITS+=("0")
  else
    EXITS+=("$?")
  fi
  NAMES+=("$name")
  DESCS+=("$desc")
  OUTPUT_FILES+=("$out")
}

# Required commands. Order: cheapest/quickest security checks first,
# then typecheck, then tests, then build.
run_cmd "audit-signatures" "npm audit signatures"  npm audit signatures
run_cmd "audit"            "npm audit"              npm audit
run_cmd "typecheck"        "npm run typecheck"      npm run typecheck
run_cmd "test"             "npm run test:run"       npm run test:run
run_cmd "build"            "npm run build"          npm run build

# Optional bounded dev-server probe (not on by default because the dev server
# is long-running; see UMBRA-INFRA-001 hook notes).
if [[ "$RUN_DEV_SMOKE" -eq 1 ]]; then
  smoke_out="$(mktemp -t umbra-verify.smoke.XXXXXX)"
  dev_log="$(mktemp -t umbra-verify.devlog.XXXXXX)"
  (
    set +e
    npm run dev >"$dev_log" 2>&1 &
    dev_pid=$!
    smoke_code=1
    for _ in 1 2 3 4 5 6 7 8; do
      sleep 1
      if curl -fsS -o /dev/null http://localhost:5173/ 2>/dev/null; then
        smoke_code=0
        break
      fi
    done
    kill "$dev_pid" 2>/dev/null
    wait "$dev_pid" 2>/dev/null
    echo "smoke exit=$smoke_code"
    echo ""
    echo "--- dev server log ---"
    cat "$dev_log"
    rm -f "$dev_log"
  ) >"$smoke_out" 2>&1
  if grep -q "smoke exit=0" "$smoke_out"; then
    EXITS+=("0")
  else
    EXITS+=("1")
  fi
  NAMES+=("dev-smoke")
  DESCS+=("optional: bounded npm run dev + curl http://localhost:5173/")
  OUTPUT_FILES+=("$smoke_out")
fi

OVERALL=0
for code in "${EXITS[@]}"; do
  if [[ "$code" -ne 0 ]]; then
    OVERALL=1
  fi
done

REPORT_FILE="$REPORT_DIR/umbra-verify-$TIMESTAMP_FILE.md"

{
  if [[ "$OVERALL" -eq 0 ]]; then
    echo "# Umbra Verification Hook — PASS"
  else
    echo "# Umbra Verification Hook — FAIL"
  fi
  echo ""
  echo "- Timestamp (UTC): $TIMESTAMP_UTC"
  echo "- Branch: \`$BRANCH\`"
  echo "- Commit: \`$COMMIT\`"
  echo "- Final status: $([[ "$OVERALL" -eq 0 ]] && echo PASS || echo FAIL)"
  echo ""
  echo "## Working tree status"
  echo ""
  echo '```text'
  echo "$GIT_STATUS"
  echo '```'
  echo ""
  echo "## Command summary"
  echo ""
  echo "| # | Command | Description | Exit | Result |"
  echo "| --- | --- | --- | --- | --- |"
  for i in "${!NAMES[@]}"; do
    idx=$((i+1))
    code="${EXITS[$i]}"
    result="pass"
    if [[ "$code" -ne 0 ]]; then
      result="fail"
    fi
    echo "| $idx | \`${NAMES[$i]}\` | ${DESCS[$i]} | $code | $result |"
  done
  echo ""
  for i in "${!NAMES[@]}"; do
    echo "## Output — \`${NAMES[$i]}\` (${DESCS[$i]})"
    echo ""
    echo "Exit code: ${EXITS[$i]}"
    echo ""
    echo '```text'
    cat "${OUTPUT_FILES[$i]}"
    echo '```'
    echo ""
  done
  echo "---"
  echo ""
  echo "Generated by \`scripts/umbra-verify.sh\`. Run \`bash scripts/umbra-verify.sh\` to reproduce."
} > "$REPORT_FILE"

# Cleanup temp files.
for f in "${OUTPUT_FILES[@]}"; do
  rm -f "$f"
done

if [[ "$OVERALL" -eq 0 ]]; then
  echo "umbra-verify: PASS — report at $REPORT_FILE"
  exit 0
else
  echo "umbra-verify: FAIL — report at $REPORT_FILE"
  exit 1
fi
